# Generated by Django 4.0.6 on 2022-07-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phyDoc_app', '0002_alter_document_details_templateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='templateid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='phyDoc_app.document_templates'),
        ),
    ]
