# Generated by Django 4.0.4 on 2022-07-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyDoc_app', '0004_alter_document_details_templateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_templates',
            name='Document_template_path',
            field=models.FileField(upload_to=''),
        ),
    ]
