# Generated by Django 4.0.1 on 2022-07-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyDoc_app', '0004_alter_document_details_templateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_templates',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
