# Generated by Django 4.0.4 on 2022-07-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyDoc_app', '0005_alter_document_templates_document_template_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_templates',
            name='Document_template_path',
            field=models.FileField(upload_to='Templates/'),
        ),
    ]
