
# Generated by Django 4.0.4 on 2022-07-13 06:35


# Generated by Django 4.0.1 on 2022-07-14 04:31



from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyDoc_app', '0007_alter_document_templates_document_template_path'),
        ('phyDoc_app', '0007_alter_document_details_id'),


    ]

    operations = [
        migrations.AlterField(
            model_name='document_templates',
            name='Document_template_path',
            field=models.FileField(upload_to='Templates/'),
        ),
    ]
