# Generated by Django 4.0.1 on 2022-07-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyDoc_app', '0009_alter_document_templates_document_template_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_templates',
            name='Document_template_path',
            field=models.FileField(upload_to=''),
        ),
    ]
