# Generated by Django 4.0.4 on 2022-07-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phyDoc_app', '0007_alter_document_details_id'),
        ('phyDoc_app', '0009_alter_document_templates_document_template_path'),
    ]

    operations = [
    ]
